[build]
  command = "bash netlify-build.sh"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  ESBUILD_BINARY_PATH = "/tmp/mock-esbuild"
  SKIP_ESBUILD = "true"
  SKIP_PREFLIGHT_CHECK = "true"

[dev]
  command = "npm run start"
  port = 8888
  targetPort = 3000
  publish = "build"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200